//pins
#define BUTTON_UP 6
#define BUTTON_DOWN 7
#define BUTTON_LEFT 8
#define BUTTON_RIGHT 9

#define SENSOR_WHEEL_PIN 0
#define SENSOR_CRANCKSET_PIN 1
#define SENSOR_WHEEL_INT 2
#define SENSOR_CRANCKSET_INT 3

#define SERVO_FRONT 10
#define SERVO_REAR 16







//config
#define LOOP_DELAY 50
#define SPEED_REFRESH 500

#define SHIFT_CORRECTION_DELAY 2500

#define SPEED_WHEELDETECTOR_CACHESIZE 40
#define SPEED_CRANCKSETDETECTOR_CACHESIZE 15
#define SPEED_WHEEL_TIMEOUT 5000
#define SPEED_CRANCKSET_TIMEOUT 3000
#define SPEED_KPH  0.06

#define SPEED_CRANCKSET_ANTISHAKE_TIMELATENCY 300
#define SPEED_WHEEL_ANTISHAKE_TIMELATENCY 50
#define ANTISHAKE_TIMELATENCY 150

#define EEPROM_SHIFTER_START 40 //need 60 address
